<?php

/**
 * @file
 * Module file Sinister Web Service.
 * Contains the resource declarations for the service APIs
 * and other commons functions/hooks. if necessary
 */

/**
 * Implements hook_services_resources().
 * Create service resource for APIs to return the necessary json data.
 */
function sinister_ws_services_resources() {
  $resources = array();

  // Include the necessary inc files.
  module_load_include('inc', 'sinister_ws', 'includes/sinister_ws.services');

  // Service Apis for contents.
  $resources = array(
    'siniestros-activos' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves Sinister Info.',
          'file' => array(
            'type' => 'inc',
            'module' => 'sinister_ws',
            'name' => 'includes/sinister_ws.services',
          ),
          'callback' => 'sinister_ws_resource_retrieve',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'Function to perform',
              'source' => array(
                'path' => '0',
              ),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
    'siniestros-terminados' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves Inactive Sinister Info.',
          'file' => array(
            'type' => 'inc',
            'module' => 'sinister_ws',
            'name' => 'includes/sinister_ws_inactive.services',
          ),
          'callback' => 'sinister_ws_inactive_resource_retrieve',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'Function to perform',
              'source' => array(
                'path' => '0',
              ),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
    'archivos' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves File Image URL.',
          'file' => array(
            'type' => 'inc',
            'module' => 'sinister_ws',
            'name' => 'includes/sinister_ws_files.services',
          ),
          'callback' => 'sinister_ws_archivos_resource_retrieve',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'nid',
              'type' => 'int',
              'description' => 'Function to perform',
              'source' => array(
                'path' => '0',
              ),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
    'vehiculos-tercero' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves Third Vehicles Info.',
          'file' => array(
            'type' => 'inc',
            'module' => 'sinister_ws',
            'name' => 'includes/sinister_ws_vehicles.services',
          ),
          'callback' => 'sinister_ws_vehicles_resource_retrieve',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'nid',
              'type' => 'int',
              'description' => 'Function to perform',
              'source' => array(
                'path' => '0',
              ),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
  );

  return $resources;
}
