<?php

/**
 * @file
 * This file has a function to delete Field Collections.
 */

/**
 * Return data from third vehicles.
 */
/*
function sinister_ws_delete_fc($nid = NULL) {

  // Assign array of field collection ids.
  $fc_ids = $_POST;

  entity_delete_multiple('field_collection_item', $fc_ids);

  $result = array(
    "This field collections have been deleted.",
    $fc_ids,
  );

  return $result;
}
*/
